name: CI
on: [push, pull_request]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: lilia

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2"

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Pull GluaCheck
        uses: actions/checkout@v3
        with:
          repository: LiliaFramework/GluaCheck
          path: luacheck

      - name: Build GluaCheck
        working-directory: luacheck
        run: luarocks make

      - name: Lint with GluaCheck
        working-directory: lilia
        run: |
          luacheck . --no-redefined \
            --no-global --no-self \
            --no-max-line-length --no-max-code-line-length \
            --no-max-string-line-length --no-max-comment-line-length \
            --no-max-cyclomatic-complexity

  glualint:
    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml@master
    needs: linter
    permissions:
      contents: write
    with:
      pretty_print: true