name: CI

on: [push, pull_request]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  prettyprint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: lilia

      - name: Download and Install GLuaLint
        run: |
          curl -L -o glualint.zip https://github.com/FPtje/GLuaFixer/releases/download/1.29.0/glualint-1.29.0-x86_64-linux.zip
          unzip glualint.zip -d glualint_folder
          chmod +x glualint_folder/glualint
          sudo mv glualint_folder/glualint /usr/local/bin
          rm -rf glualint.zip glualint_folder

      - name: Lint with GLuaLint
        run: |
          cd lilia
          glualint --pretty-print lilia

      - name: Configure Git
        run: |
          git config --global user.email "githubactions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.LiliaGitSecret }}
        run: |
          cd lilia
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Pretty Printed"
            git push https://${{ secrets.LiliaGitSecret }}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi